# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(810, 724)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.widget_5 = QtGui.QWidget(self.groupBox_3)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboBox = QtGui.QComboBox(self.widget_5)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.pushButton_7 = QtGui.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.widget_3 = QtGui.QWidget(self.groupBox_3)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout = QtGui.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.widget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox_2.setMaximum(360.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout.addWidget(self.doubleSpinBox_2, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.widget_3)
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setMaximum(90.0)
        self.doubleSpinBox.setProperty("value", 45.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 0, 4, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setStrikeOut(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 1, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.operation_start_button = QtGui.QPushButton(self.groupBox)
        self.operation_start_button.setObjectName(_fromUtf8("operation_start_button"))
        self.horizontalLayout_2.addWidget(self.operation_start_button)
        self.operation_stop_button = QtGui.QPushButton(self.groupBox)
        self.operation_stop_button.setEnabled(False)
        self.operation_stop_button.setObjectName(_fromUtf8("operation_stop_button"))
        self.horizontalLayout_2.addWidget(self.operation_stop_button)
        self.operation_status_label = QtGui.QLabel(self.groupBox)
        self.operation_status_label.setObjectName(_fromUtf8("operation_status_label"))
        self.horizontalLayout_2.addWidget(self.operation_status_label)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.widget = QtGui.QWidget(self.groupBox_4)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.frame)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.verticalLayout_3.addWidget(self.dateTimeEdit)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.frame)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.verticalLayout_3.addWidget(self.dateTimeEdit_2)
        self.radioButton_5 = QtGui.QRadioButton(self.frame)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_4.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.line = QtGui.QFrame(self.groupBox_5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.db_get_button = QtGui.QPushButton(self.groupBox_7)
        self.db_get_button.setObjectName(_fromUtf8("db_get_button"))
        self.verticalLayout_7.addWidget(self.db_get_button)
        self.db_past_button = QtGui.QPushButton(self.groupBox_7)
        self.db_past_button.setObjectName(_fromUtf8("db_past_button"))
        self.verticalLayout_7.addWidget(self.db_past_button)
        self.gridLayout_2.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_10.addWidget(self.groupBox_10)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.hv_slider = QtGui.QSlider(self.groupBox_9)
        self.hv_slider.setOrientation(QtCore.Qt.Horizontal)
        self.hv_slider.setObjectName(_fromUtf8("hv_slider"))
        self.horizontalLayout_4.addWidget(self.hv_slider)
        self.hv_spinbutton = QtGui.QSpinBox(self.groupBox_9)
        self.hv_spinbutton.setObjectName(_fromUtf8("hv_spinbutton"))
        self.horizontalLayout_4.addWidget(self.hv_spinbutton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addWidget(self.groupBox_9)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_9.addWidget(self.label_15)
        self.line_2 = QtGui.QFrame(self.groupBox_6)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_9.addWidget(self.line_2)
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_9.addWidget(self.label_7)
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_9.addWidget(self.label_11)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_9.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_9.addWidget(self.label_14)
        self.verticalLayout_8.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_4 = QtGui.QWidget(self.groupBox_2)
        self.widget_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_4 = QtGui.QPushButton(self.widget_4)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.widget_4)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton = QtGui.QPushButton(self.widget_4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConfiguration = QtGui.QAction(MainWindow)
        self.actionConfiguration.setObjectName(_fromUtf8("actionConfiguration"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionCheck_for_updates = QtGui.QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName(_fromUtf8("actionCheck_for_updates"))
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheck_for_updates)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionConfiguration)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Set up", None))
        self.label_3.setText(_translate("MainWindow", "Locale:", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Add new...", None))
        self.pushButton_7.setText(_translate("MainWindow", "Detect", None))
        self.label_4.setText(_translate("MainWindow", "Alt-azimuthal coordinates (degrees):", None))
        self.label_6.setText(_translate("MainWindow", "Azimuth:", None))
        self.label_5.setText(_translate("MainWindow", "Altitude:", None))
        self.pushButton_6.setText(_translate("MainWindow", "Detect", None))
        self.pushButton_8.setText(_translate("MainWindow", "Move to", None))
        self.label_19.setText(_translate("MainWindow", "Last used settings:", None))
        self.groupBox.setTitle(_translate("MainWindow", "Operation", None))
        self.operation_start_button.setText(_translate("MainWindow", "Start", None))
        self.operation_stop_button.setText(_translate("MainWindow", "Stop", None))
        self.operation_status_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Stopped.</span></p></body></html>", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Display results", None))
        self.radioButton.setText(_translate("MainWindow", "Past minute", None))
        self.radioButton_2.setText(_translate("MainWindow", "Past hour", None))
        self.radioButton_3.setText(_translate("MainWindow", "Past day", None))
        self.radioButton_4.setText(_translate("MainWindow", "Custom interval", None))
        self.label_2.setText(_translate("MainWindow", "Start:", None))
        self.label.setText(_translate("MainWindow", "End:", None))
        self.radioButton_5.setText(_translate("MainWindow", "Now", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Run", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Database status", None))
        self.label_12.setText(_translate("MainWindow", "First event:", None))
        self.label_9.setText(_translate("MainWindow", "Last event:", None))
        self.label_8.setText(_translate("MainWindow", "Number of recorded events:", None))
        self.label_10.setText(_translate("MainWindow", "Database size:", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Results", None))
        self.db_get_button.setText(_translate("MainWindow", "Export from database", None))
        self.db_past_button.setText(_translate("MainWindow", "View past aquisitions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Database", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Address", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Read", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Set", None))
        self.pushButton_2.setText(_translate("MainWindow", "Auto -calibrate HV ", None))
        self.pushButton_3.setText(_translate("MainWindow", "Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "High Voltage", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Event rates", None))
        self.label_15.setText(_translate("MainWindow", "Overall event rate:", None))
        self.label_7.setText(_translate("MainWindow", "Event rate history:", None))
        self.label_11.setText(_translate("MainWindow", "Event rates by elevation:", None))
        self.label_13.setText(_translate("MainWindow", "Event rates by location:", None))
        self.label_14.setText(_translate("MainWindow", "Event rates by ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Statistics", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preview", None))
        self.pushButton_4.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_5.setText(_translate("MainWindow", "Export As...", None))
        self.pushButton.setText(_translate("MainWindow", "Change axis label", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionImport.setText(_translate("MainWindow", "Import...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionConfiguration.setText(_translate("MainWindow", "Configuration", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionManual.setText(_translate("MainWindow", "Manual", None))
        self.actionCheck_for_updates.setText(_translate("MainWindow", "Check for updates", None))

